In [3]:
from minimal_effects_randomizer import meRandomize
import numpy as np

# 50 subjects for 6 conditions
m = 50
n = 6

draws = meRandomize(m,n)

# Test if subsequent condition appear equally as often
draws_sequence = np.zeros([n,n])
for draw in draws:
	for idx in range(len(draw)):
		draws_sequence[draw[idx-1 if idx>0 else n-1],draw[idx]] += 1

        
# Test if each condition appears at each postion equally as often
draws_position = np.zeros([n,n])
for idx in range(n):
	uni, count = np.unique(np.array(draws)[:,idx],return_counts=True)
	draws_position[uni,idx] = count

print('In sequence:')
print(draws_sequence)
print()
print('In position:')
print(draws_position)
print()
draws

In sequence:
[[ 0. 10. 11. 10. 10.  9.]
 [10.  0.  9. 10. 10. 11.]
 [10. 10.  0. 10. 10. 10.]
 [10. 10. 10.  0. 10. 10.]
 [10. 10. 10. 10.  0. 10.]
 [10. 10. 10. 10. 10.  0.]]

In position:
[[8. 7. 9. 9. 8. 9.]
 [8. 9. 8. 8. 8. 9.]
 [8. 8. 9. 9. 8. 8.]
 [9. 9. 8. 8. 8. 8.]
 [9. 8. 8. 8. 9. 8.]
 [8. 9. 8. 8. 9. 8.]]



[[4, 3, 0, 5, 1, 2],
 [2, 0, 3, 1, 4, 5],
 [0, 2, 1, 3, 5, 4],
 [3, 4, 2, 5, 0, 1],
 [4, 1, 5, 3, 2, 0],
 [1, 0, 4, 2, 3, 5],
 [1, 5, 2, 4, 0, 3],
 [5, 4, 3, 0, 1, 2],
 [2, 3, 4, 1, 5, 0],
 [3, 2, 1, 0, 4, 5],
 [0, 5, 1, 4, 2, 3],
 [3, 1, 0, 2, 5, 4],
 [1, 4, 5, 0, 3, 2],
 [2, 0, 5, 3, 4, 1],
 [5, 2, 4, 0, 1, 3],
 [4, 5, 2, 1, 3, 0],
 [5, 3, 4, 2, 0, 1],
 [0, 2, 3, 5, 1, 4],
 [4, 1, 0, 3, 2, 5],
 [2, 5, 0, 4, 3, 1],
 [5, 1, 3, 2, 4, 0],
 [3, 0, 1, 5, 2, 4],
 [1, 4, 2, 0, 5, 3],
 [0, 3, 5, 4, 1, 2],
 [3, 4, 5, 1, 0, 2],
 [5, 0, 2, 1, 4, 3],
 [1, 2, 3, 4, 5, 0],
 [2, 1, 0, 5, 3, 4],
 [0, 4, 1, 3, 2, 5],
 [5, 2, 4, 0, 3, 1],
 [4, 3, 1, 2, 0, 5],
 [1, 5, 2, 3, 0, 4],
 [3, 5, 4, 2, 1, 0],
 [4, 0, 3, 2, 5, 1],
 [0, 1, 2, 4, 5, 3],
 [1, 3, 0, 5, 4, 2],
 [2, 4, 5, 3, 1, 0],
 [2, 5, 0, 1, 4, 3],
 [1, 3, 4, 0, 2, 5],
 [4, 1, 3, 5, 2, 0],
 [3, 1, 5, 4, 0, 2],
 [5, 0, 1, 2, 3, 4],
 [3, 2, 4, 1, 0, 5],
 [0, 4, 3, 5, 2, 1],
 [4, 2, 0, 3, 5, 1],
 [0, 3, 2, 1, 5, 4],
 [2, 5, 1, 4, 3, 0],
 [3, 1, 5, 0,